### ISSUE TITLE
Need to work on validating the authorization header token in client and server MERN

### ISSUE THREAD

**Issue by isNan909** [ishan-me/FullMERN_auth#1]
This is a remaining task I need to complete on this. If you are interested you can work on validating the authorization header in client and server. This is MERN stack authentication demo implementation.

The current code is not secure.

**Comment by nikhil-chacko** [comment]
I would like to work on this issue

**Comment by rahulvermafreelancer** [comment]
Hello, I want to work on this project. Can i work on that if you give permission so that i can?

**Comment by isNan909** [comment]
@rahulvermafreelancer @Nikhil-dev13 You can both work on this, send me your PR.

**Comment by nikhil-chacko** [comment]
I will make a PR probably by EOD or tomorrow @ishan-me

**Comment by isNan909** [comment]
@Nikhil-dev13 Thankyou for your awesome work. I will close down this PR once I receive PR also from @rahulvermafreelancer 

Thank you so much.

**Comment by isNan909** [comment]
The enhancement feature is closed Thankyou for your valuable contribution @Nikhil-dev13
